# ~/.config/tmuxinator/dotfiles.yml

name: config
root: ~/.config

windows:
  - editor:
      panes:
        - while true; do nvim .; done
  - console:
  - yazi:
      panes:
        - while true; do yazi; done
