[[mgr.prepend_keymap]]
on = [ "c", "x" ]
run = 'shell "chmod +x $@" --confirm'
desc = "Make executable"

[[mgr.prepend_keymap]]
on = [ "c", "6" ]
run = 'shell "chmod 644 $@" --confirm'
desc = "Set permissions to 644"

[[mgr.prepend_keymap]]
on = [ "c", "7" ]
run = 'shell "chmod 755 $@" --confirm'
desc = "Set permissions to 755"

[[mgr.prepend_keymap]]
on = [ "c", "m" ]
run = "plugin chmod"
desc = "Change file permissions"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dev"
desc = "Go to ~/dev"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Downloads"
desc = "Go to ~/Downloads"

[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "noop"
desc = "Disabled: Enter key use 'o' instead"

[[mgr.prepend_keymap]]
on = [ "?" ]
run = "help"
desc = "Open help menu"

# vim motion bindings
[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
